baseurl = "http://www.ferzerkerx.com/"
title = "ferzerkerx"
languageCode = "en-us"
theme = "personal-theme"
copyright = "&copy; 2016 Fernando Montes"


[params]
max_post_count=10


[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 2