baseurl = "http://ferzerkerx.github.io/site/"
title = "Ferzerkerx"
languageCode = "en-us"
theme = "personal-theme"
copyright = "&copy; Fernando Montes"


[params]


[[menu.main]]
  name = "Projects"
  url = "/project/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true