baseurl = "http://www.ferzerkerx.com/"
title = "ferzerkerx"
languageCode = "en-us"
theme = "personal-theme"

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 2